config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :playlists, only: [:index, :create, :update, :destroy]
  resources :tracks, only: [:index, :create, :destroy]

  namespace :api do
    namespace :v1 do
      resources :playlists, only: [:index, :create, :destroy, :update]
    end
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root to:"home#show"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/playlist.rb
class Playlist < ApplicationRecord
  validates :name, presence: true, length: {minimum:3}, uniqueness: true

  belongs_to :user

  scope :by_recently_created, -> { order(created_at: :desc) }

  def active?
    self.active == true
  end

  def inactive?
    self.active == false
  end
end

app/models/track.rb
class Track < ApplicationRecord
  belongs_to :user

  validates :filename, presence: true

  scope :by_recent, -> { order(created_at: :desc) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  has_many :playlists, dependent: :delete_all
  has_many :tracks, dependent: :destroy

  def active_playlist
    playlists.where(active: true).first
  end
end

app/controllers/api/v1/playlists_controller.rb
module Api
  module V1
    class PlaylistsController < ApplicationController
      # TODO: Add API login along side web authentication in order to be allowed to upload file

      include Concerns::NotFound
      include Concerns::HasPlaylist

      skip_before_action :verify_authenticity_token
      before_action :set_playlist, only: [:destroy, :update, :show]

      def index
        @playlists = Playlist.by_recently_created

        render json: @playlists, each_serializer: PlaylistSerializer
      end

      def create
        set_inactive
        playlist = Playlist.new(playlist_params.merge(active: true, user_id: User.first.id))

        if playlist.save
          render json: playlist, serialize: PlaylistSerializer, status: 201
        else
          render json: {errors: playlist.errors.full_messages}, status: 422
        end
      end

      def update
        set_inactive
        @playlist.update_attribute(:active, true)

        render json: @playlist, serialize: PlaylistSerializer, status: 200
      end

      def destroy
        @playlist.destroy

        render json: { message: "Playlist destroyed" }, status: 200
      end

      def show
        # used for display Audio songs
      end

      private

      def set_playlist
        @playlist = Playlist.find(params[:id])
      rescue ActiveRecord::RecordNotFound
        handle_not_found
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concerns/concerns/has_playlist.rb
module Concerns
  module HasPlaylist
    extend ActiveSupport::Concern

    private

    def playlist_params
      params.require(:playlist).permit(:name, :active, :created_at, :user_id)
    end

    def set_inactive
      Playlist.all.update_all(active: false)
    end
  end
end

app/controllers/concerns/concerns/not_found.rb
module Concerns
  module NotFound
    extend ActiveSupport::Concern

    private

    def handle_not_found(klass_or_message = Playlist, custom_message = false)
      message = if klass_or_message.is_a?(String)
        klass_or_message
      else
        klass_or_message.name.demodulize.titleize
      end

      message += " not found" unless custom_message

      render json: message.to_json, status: 422
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
    render
  end
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  include Concerns::HasPlaylist

  before_action :authenticate_user!
  before_action :set_playlist, only: [:update, :show, :destroy]

  def index
    @playlists = Playlist.by_recently_created.where(user_id: current_user.id)

    render
  end

  def create
    set_inactive

    @playlist = Playlist.new(playlist_params.merge(active: true, user_id: current_user.id))

    if @playlist.save
      redirect_to playlists_path, notice: "Playlist created"
    else
      @playlist = Playlist.new
      redirect_to playlists_path, error: "Playlist created"
    end
  end

  def update
    set_inactive

    @playlist.update_attribute(:active, true)
    flash[:notice] = "Playlist activated!"
    redirect_to playlists_path
  end

  def show
    # used for diplay Playlist page, where the user will add songs
  end

  def destroy
    @playlist.destroy

    flash[:notice] = "Playlist deleted!"
    redirect_to playlists_path
  end

  private

  def set_playlist
    @playlist = Playlist.find(params[:id])
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :authenticate_user!

  def index
    @tracks = Track.by_recent.where(user_id: current_user.id)
  end

  def create
  end

  def destroy
  end

  private

  def track_params
    params.require(:track).permit(:song)
  end
end

app/helpers/api/v1/playlists_helper.rb
module Api::V1::PlaylistsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_path?(path)
    request.fullpath == path
  end

  def active_path(path)
    return "active" if current_path?(path)

    ""
  end
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
  def button_text(playlist)
    playlist.active? ? 'Active' : 'Set Active'
  end
end

app/views/home/index.html.erb
<h1>Home</h1>

app/views/home/show.html.erb
<h1>Homw</h1>

app/views/layouts/_navigation.html.erb
<div class="navigation">
  <div class="brand">
    Track-er
  </div>
  <ul>
    <% if user_signed_in? %>
      <li>
        <%= link_to "Playlists", playlists_path, class: "#{active_path(playlists_path)}" %>
      </li>
      <li>
        <%= link_to "Songs List", tracks_path, class: "#{active_path(tracks_path)}" %>
      </li>
      <li>
        <%= button_to "Logout", destroy_user_session_path, :method => :delete %>
      </li>
    <% else %>
      <li>
        <%= link_to "Login", new_user_session_path, class: "#{active_path(new_user_session_path)}" %>
      </li>
    <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestRor</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/navigation" %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/playlists/_form.html.erb
<div class="form-container">
  <%= form_for :playlist do |f| %>
    <div>
      <%= f.text_field :name %>
    </div>
    <%= f.submit %>
  <% end %>
</div>

app/views/playlists/index.html.erb
<h1>Playlists</h1>
<% count = 1 %>
<% @playlists.each_with_index do |playlist, i| %>
  <div>
    <%= count += i %>.
    <%= playlist.name %>
    <%= button_to button_text(playlist), playlist_path(playlist.id), :disabled => playlist.active, :method => :patch %>
    <%= button_to 'Remove', playlist_path(playlist.id), :method => :delete %>
  </div>
<% end %>

<%= render "playlists/form" %>

app/views/tracks/index.html.erb
<h1>Songs page</h1>